# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cartela_pb2 as cartela__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cartela_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class cartelaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendVencedor = channel.unary_unary(
                '/cartela.cartelaService/SendVencedor',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=cartela__pb2.Vencedor.FromString,
                _registered_method=True)
        self.SendCartela = channel.unary_unary(
                '/cartela.cartelaService/SendCartela',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=cartela__pb2.CartelasList.FromString,
                _registered_method=True)
        self.SendCartelaAtualizada = channel.unary_unary(
                '/cartela.cartelaService/SendCartelaAtualizada',
                request_serializer=cartela__pb2.RequestNumber.SerializeToString,
                response_deserializer=cartela__pb2.CartelasList.FromString,
                _registered_method=True)


class cartelaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendVencedor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCartela(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCartelaAtualizada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cartelaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendVencedor': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVencedor,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=cartela__pb2.Vencedor.SerializeToString,
            ),
            'SendCartela': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCartela,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=cartela__pb2.CartelasList.SerializeToString,
            ),
            'SendCartelaAtualizada': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCartelaAtualizada,
                    request_deserializer=cartela__pb2.RequestNumber.FromString,
                    response_serializer=cartela__pb2.CartelasList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cartela.cartelaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cartela.cartelaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class cartelaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendVencedor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cartela.cartelaService/SendVencedor',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            cartela__pb2.Vencedor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCartela(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cartela.cartelaService/SendCartela',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            cartela__pb2.CartelasList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCartelaAtualizada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cartela.cartelaService/SendCartelaAtualizada',
            cartela__pb2.RequestNumber.SerializeToString,
            cartela__pb2.CartelasList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
