# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cartela.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cartela.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcartela.proto\x12\x07\x63\x61rtela\x1a\x1bgoogle/protobuf/empty.proto\"t\n\x07\x43\x61rtela\x12\x0f\n\x07usuario\x18\x01 \x01(\x05\x12*\n\x05\x63\x61mpo\x18\x19 \x03(\x0b\x32\x1b.cartela.Cartela.CampoEntry\x1a,\n\nCampoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1b\n\x08Vencedor\x12\x0f\n\x07usuario\x18\x01 \x01(\x05\"\x1f\n\rRequestNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"2\n\x0c\x43\x61rtelasList\x12\"\n\x08\x63\x61rtelas\x18\x01 \x03(\x0b\x32\x10.cartela.Cartela2\xd1\x01\n\x0e\x63\x61rtelaService\x12\x39\n\x0cSendVencedor\x12\x16.google.protobuf.Empty\x1a\x11.cartela.Vencedor\x12<\n\x0bSendCartela\x12\x16.google.protobuf.Empty\x1a\x15.cartela.CartelasList\x12\x46\n\x15SendCartelaAtualizada\x12\x16.cartela.RequestNumber\x1a\x15.cartela.CartelasListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartela_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTELA_CAMPOENTRY']._loaded_options = None
  _globals['_CARTELA_CAMPOENTRY']._serialized_options = b'8\001'
  _globals['_CARTELA']._serialized_start=55
  _globals['_CARTELA']._serialized_end=171
  _globals['_CARTELA_CAMPOENTRY']._serialized_start=127
  _globals['_CARTELA_CAMPOENTRY']._serialized_end=171
  _globals['_VENCEDOR']._serialized_start=173
  _globals['_VENCEDOR']._serialized_end=200
  _globals['_REQUESTNUMBER']._serialized_start=202
  _globals['_REQUESTNUMBER']._serialized_end=233
  _globals['_CARTELASLIST']._serialized_start=235
  _globals['_CARTELASLIST']._serialized_end=285
  _globals['_CARTELASERVICE']._serialized_start=288
  _globals['_CARTELASERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
