# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bingo_pb2 as bingo__pb2


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/bingo.GameService/CreateGame',
                request_serializer=bingo__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=bingo__pb2.CreateGameResponse.FromString,
                )
        self.RegisterPlayer = channel.unary_unary(
                '/bingo.GameService/RegisterPlayer',
                request_serializer=bingo__pb2.RegisterPlayerRequest.SerializeToString,
                response_deserializer=bingo__pb2.RegisterPlayerResponse.FromString,
                )
        self.DrawNumber = channel.unary_unary(
                '/bingo.GameService/DrawNumber',
                request_serializer=bingo__pb2.DrawNumberRequest.SerializeToString,
                response_deserializer=bingo__pb2.DrawNumberResponse.FromString,
                )
        self.MarkNumber = channel.unary_unary(
                '/bingo.GameService/MarkNumber',
                request_serializer=bingo__pb2.MarkNumberRequest.SerializeToString,
                response_deserializer=bingo__pb2.MarkNumberResponse.FromString,
                )
        self.CheckBingo = channel.unary_unary(
                '/bingo.GameService/CheckBingo',
                request_serializer=bingo__pb2.CheckBingoRequest.SerializeToString,
                response_deserializer=bingo__pb2.CheckBingoResponse.FromString,
                )


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrawNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBingo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=bingo__pb2.CreateGameRequest.FromString,
                    response_serializer=bingo__pb2.CreateGameResponse.SerializeToString,
            ),
            'RegisterPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlayer,
                    request_deserializer=bingo__pb2.RegisterPlayerRequest.FromString,
                    response_serializer=bingo__pb2.RegisterPlayerResponse.SerializeToString,
            ),
            'DrawNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.DrawNumber,
                    request_deserializer=bingo__pb2.DrawNumberRequest.FromString,
                    response_serializer=bingo__pb2.DrawNumberResponse.SerializeToString,
            ),
            'MarkNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkNumber,
                    request_deserializer=bingo__pb2.MarkNumberRequest.FromString,
                    response_serializer=bingo__pb2.MarkNumberResponse.SerializeToString,
            ),
            'CheckBingo': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBingo,
                    request_deserializer=bingo__pb2.CheckBingoRequest.FromString,
                    response_serializer=bingo__pb2.CheckBingoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bingo.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.GameService/CreateGame',
            bingo__pb2.CreateGameRequest.SerializeToString,
            bingo__pb2.CreateGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.GameService/RegisterPlayer',
            bingo__pb2.RegisterPlayerRequest.SerializeToString,
            bingo__pb2.RegisterPlayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DrawNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.GameService/DrawNumber',
            bingo__pb2.DrawNumberRequest.SerializeToString,
            bingo__pb2.DrawNumberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarkNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.GameService/MarkNumber',
            bingo__pb2.MarkNumberRequest.SerializeToString,
            bingo__pb2.MarkNumberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckBingo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.GameService/CheckBingo',
            bingo__pb2.CheckBingoRequest.SerializeToString,
            bingo__pb2.CheckBingoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ValidationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateNumber = channel.unary_unary(
                '/bingo.ValidationService/ValidateNumber',
                request_serializer=bingo__pb2.ValidateNumberRequest.SerializeToString,
                response_deserializer=bingo__pb2.ValidateNumberResponse.FromString,
                )
        self.ValidateBingo = channel.unary_unary(
                '/bingo.ValidationService/ValidateBingo',
                request_serializer=bingo__pb2.ValidateBingoRequest.SerializeToString,
                response_deserializer=bingo__pb2.ValidateBingoResponse.FromString,
                )
        self.GetCard = channel.unary_unary(
                '/bingo.ValidationService/GetCard',
                request_serializer=bingo__pb2.GetCardRequest.SerializeToString,
                response_deserializer=bingo__pb2.GetCardResponse.FromString,
                )
        self.RegisterCard = channel.unary_unary(
                '/bingo.ValidationService/RegisterCard',
                request_serializer=bingo__pb2.RegisterCardRequest.SerializeToString,
                response_deserializer=bingo__pb2.RegisterCardResponse.FromString,
                )


class ValidationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateBingo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCard(self, request, context):
        """🔥 Novo RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateNumber,
                    request_deserializer=bingo__pb2.ValidateNumberRequest.FromString,
                    response_serializer=bingo__pb2.ValidateNumberResponse.SerializeToString,
            ),
            'ValidateBingo': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateBingo,
                    request_deserializer=bingo__pb2.ValidateBingoRequest.FromString,
                    response_serializer=bingo__pb2.ValidateBingoResponse.SerializeToString,
            ),
            'GetCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCard,
                    request_deserializer=bingo__pb2.GetCardRequest.FromString,
                    response_serializer=bingo__pb2.GetCardResponse.SerializeToString,
            ),
            'RegisterCard': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCard,
                    request_deserializer=bingo__pb2.RegisterCardRequest.FromString,
                    response_serializer=bingo__pb2.RegisterCardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bingo.ValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.ValidationService/ValidateNumber',
            bingo__pb2.ValidateNumberRequest.SerializeToString,
            bingo__pb2.ValidateNumberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateBingo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.ValidationService/ValidateBingo',
            bingo__pb2.ValidateBingoRequest.SerializeToString,
            bingo__pb2.ValidateBingoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.ValidationService/GetCard',
            bingo__pb2.GetCardRequest.SerializeToString,
            bingo__pb2.GetCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.ValidationService/RegisterCard',
            bingo__pb2.RegisterCardRequest.SerializeToString,
            bingo__pb2.RegisterCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
